### PR TITLE
Cauldron Meta Implementation

### PR DESCRIPTION
**Pull request by erosemberg**

### CODE REVIEW

**Comment by mkotb** [comment]
Could you possibly squash those 2 commits?

**Comment by erosemberg** [comment]
@mkotb What do you mean by Squash those commits

**Comment by AgentTroll** [comment]
Merge the two commits into one.

**Comment by erosemberg** [comment]
For some reason it's not letting me merge those 2 commits.

**Comment by mythbusterma** [comment]
That's because its not a "merge."

You do an interactive rebase from your branch to ours and then either fixup
or squash the commits so that there's only one.

**Comment by erosemberg** [comment]
I did do a rebase but it keeps failing.

**Comment by AgentTroll** [comment]
Your local copy might not be up to date

**Comment by erosemberg** [comment]
It's the latest update

**Comment by AgentTroll** [comment]
@erosemberg Alright, it's fine. Please update TridentSDK/TridentSDK#52

**Pull request merged**
