### PR TITLE
Fix ExecutorTest.. Factories ain't a thing no' mo'

### PR DESCRIPTION
**Pull request by nickrobson**
This should be done. Really.

### CODE REVIEW

**Comment by nickrobson** [comment]
clazzic. thanks travis for making it look like i dont know java.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project trident: Failed to deploy artifacts: Could not transfer artifact net.tridentsdk:trident:jar:0.3-20150809.072920-40 from/to tridentsdk-central (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/net/tridentsdk/trident/0.3-SNAPSHOT/trident-0.3-20150809.072920-40.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

**Comment by mkotb** [comment]
Does the test succeed with these changes?

**Comment by AgentTroll** [comment]
Or you can run it yourself mate

**Comment by Vilsol** [comment]
Pull the latest changes from central, to your branch, should fix the build error

**Comment by nickrobson** [comment]
Yeah, test works with these changes.. Travis also says it does (right above where it makes the jar)

**Pull request merged**
