### PR TITLE
Implementation of Titles and Bars.

### PR DESCRIPTION
**Pull request by PizzaCrust**
This implements https://github.com/TridentSDK/TridentSDK/pull/53 and https://github.com/TridentSDK/TridentSDK/pull/54.

I couldn't test it because it seems events are not working?

### CODE REVIEW

**Comment by Vilsol** [comment]
Really nice, though, for the enum, why did you override the toString() method? It might be used by someone at some point, so rather just use String.valueOf() everywhere where you need a string.

**Comment by PizzaCrust** [comment]
Will do.

**Comment by Vilsol** [comment]
No, you didn't understand, there is no point overriding anything, just remove the override all together. If anyone will desperately need the string version, they will just use String.valueOf() on the actual integer.

**Comment by PizzaCrust** [comment]
Pushed.

**Pull request merged**
