### PR TITLE
Switch Trident to Java 8

### PR DESCRIPTION
**Pull request by MazenMC**
In this PR, we do the following:
* Change Trident to use Java 8
* Switch applicable for-loops or searches to use streams
* Switch applicable anonymous classes to use lambdas
* Make improvements to ProtocolMetadata, use encoding to save memory
* Merge master

### CODE REVIEW

**Comment by Twister915** [comment]
I'd like to object to this. It'd be far better if Trident were compatible with older versions of Java so that server owners and plugin developers can make their plugins compatible with more versions of java instead of being limited to 8+.

**Comment by MazenMC** [comment]
@Twister915 There are a few things I would like to comment on why I purpose such a decision:
* Trident looks to do what would benefit most server owners and developers, and within our research we have seen most server owners are _usually_ 1 update behind. To our expectations, when we can release Trident to a production environment and ready to impress, Java 9 would be in the process of being widely distributed (as we can see its very fast progress already).
* Java 8 provides many more high level concurrency classes which can help us ensure thread safety to a further extent than we can now
* While your point is very valid in terms of allowing backwards compatible plugins, there is only a certain limit we can go to.

**Comment by Twister915** [comment]
@MazenMC 

As to point one, your evidence does not support your initial statement. The farther back you go the more benefit you will see for both server owners and developers. The other two arguments you have for this are valid and I cannot argue. There are many reasons you'd want to use 8 and many reasons you'd want to bind against earlier versions, I just wanted to make sure you were analyzing both before deciding to jump forward with a switch to 8.

**Comment by AgentTroll** [comment]
I expect this to be pulled after we dissect some MCStats statistics after Java 9 is officially released to all platforms.

**Comment by MazenMC** [comment]
@AgentTroll We have to take a look towards when the project has matured and is ready for production, at that point Java 9 would be in the progress of being distributed to all platforms. Due to such, I believe it is the best decision to plan ahead due to the benefits we will receive now. I hope this is pulled when we can come to the verdict that this is the right path and is beneficial to do ahead of time.

**Comment by MazenMC** [comment]
The project compiles, seems Travis is acting up.

**Comment by aaomidi** [comment]
thx

**Comment by caojohnny** [comment]
No prob

**Comment by Vilsol** [comment]
we should rewrite it

**Comment by caojohnny** [comment]
`git checkout -b revamp-of-revamp`

**Pull request merged**
